name: dartmotion
description: A demonstration game to demonstrate device orientation using Dart.
version: 0.3.1
homepage: https://github.com/nkratzke/dartmotion
author: Nane Kratzke <nane.kratzke@th-luebeck.de>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  pwa: '>=0.1.2 <0.3.0'

dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=1.2.0 <3.0.0"
